plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-cayman
title: Expressly Express
baseurl: "education-expressly-express"
url: ""
